backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/comics
public_folder: /img

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "comics"
    label: "Comics"
    label_singular: "Comic"
    folder: "content/comics"
    create: true
    slug: "{{slug}}"
    editor:
     preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
